import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});
import { SpeedInsights } from "@vercel/speed-insights/next";
import AuthProvider from "@/AuthProvider/AuthProvider";
import { AuthorProvider } from "@/ContextAPI/AuthContext";
import { CheckProvider } from "@/ContextAPI/CheckSetContext";
// import Navbar from './Components/Navbar'
export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <CheckProvider>
          <AuthorProvider>
            <AuthProvider>{children}</AuthProvider>
          </AuthorProvider>
        </CheckProvider>

        <SpeedInsights />
      </body>
    </html>
  );
}
